# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo/hugo_extended:0.62.2

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
- apk --quiet --no-progress update
- apk --quiet --no-progress --no-cache add make git

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
